#!/usr/bin/env bash

# Step 1: Stop Nginx
service nginx stop

# Step 2: Modify Nginx configuration to listen on port 80
sed -i 's/listen 80;/listen 0.0.0.0:80;/g' /etc/nginx/conf.d/default.conf

# Step 3: Start Nginx
service nginx start

# Step 4: Check Nginx is listening on port 80
netstat -tulnp | grep nginx
